// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbrbxbgafpljbhcgwylm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicmJ4YmdhZnBsamJoY2d3eWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODA5NTUsImV4cCI6MjA5MTY1Njk1NX0.4hTSsHbwmMiLsQ0_3tcVfZbitkeki85sLcaFJ6L9_EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});