// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbrbxbgafpljbhcgwylm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicmJ4YmdhZnBsamJoY2d3eWxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwODA5NTUsImV4cCI6MjA5MTY1Njk1NX0.4hTSsHbwmMiLsQ0_3tcVfZbitkeki85sLcaFJ6L9_EU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const REMEMBER_KEY = "sprint-dnb-remember-me";

export const setRememberMe = (remember: boolean) => {
  try {
    if (remember) localStorage.setItem(REMEMBER_KEY, "1");
    else localStorage.removeItem(REMEMBER_KEY);
  } catch {}
};

const isRemembered = () => {
  try {
    return localStorage.getItem(REMEMBER_KEY) === "1";
  } catch {
    return true;
  }
};

// Custom storage: writes session to localStorage when "remember me" is on,
// otherwise to sessionStorage (cleared when the browser/tab closes).
// Reads check both stores so existing sessions keep working.
const hybridStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key) ?? sessionStorage.getItem(key);
    } catch {
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      if (isRemembered()) {
        localStorage.setItem(key, value);
        sessionStorage.removeItem(key);
      } else {
        sessionStorage.setItem(key, value);
        localStorage.removeItem(key);
      }
    } catch {}
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
      sessionStorage.removeItem(key);
    } catch {}
  },
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: hybridStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});